name: S3 Deploy
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches:
      - 'main'

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Check Memory
        run: free -m
      - name: Build App
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
        run: npm run build
      - name: Run Tests
        run: npm test
      - name: Push to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2' # optional: defaults to us-east-1
          SOURCE_DIR: 'dist' # optional: defaults to entire repository
      # - name: Bump Version and Push Tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     # dry_run: true
      - name: Bump Version
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          # skip-tag: 'true'
      - name: List Files
        run: ls ${{ github.workspace }}
      # - name: 'Build Changelog'
      #   id: build_changelog
      #   uses: mikepenz/release-changelog-builder-action@v3
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: v0.0.1
      #     release_name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.build_changelog.outputs.changelog }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
